apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-beta
      containers:
      - name: springboot-app
        image: youssefkentari/springboot-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/my_database"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "0000"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30090  # Port entre 30000-32767

