name: Deploy to Kubernetes
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Install required system packages
        run: |
          if ! command -v tar &> /dev/null; then
            echo "Installing tar..."
            sudo apt-get update
            sudo apt-get install -y tar
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build JAR file
        run: mvn clean package -DskipTests

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest

      - name: Test Kubernetes Connection
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/mysql.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout restart deployment/springboot-app
