name: Deploy to Kubernetes
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build JAR file
        run: mvn clean package -DskipTests

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest

      - name: Test Kubernetes Connection
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/mysql.yaml
          kubectl apply -f k8s/deploy_worker_beta.yaml
          kubectl apply -f k8s/deploy_worker_alpha.yaml
