name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build JAR file
      run: mvn clean package -DskipTests

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest

    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        chmod +x kind
        sudo mv kind /usr/local/bin/
      
    - name: Install kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Create Kubernetes Cluster
      run: |
        kind create cluster --name my-cluster
      
    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        kind get kubeconfig --name my-cluster > $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-mysql.yaml
        kubectl apply -f k8s-deployment.yaml
        kubectl rollout status deployment/springboot-app

    - name: Destroy Kind cluster
      run: kind delete cluster --name my-cluster
