name: Deploy to Kubernetes 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build JAR file
      run: mvn clean package -DskipTests

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Test Kubernetes Connection
      run: kubectl cluster-info  # This should work now
      
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/mysql.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl rollout restart deployment/springboot-app

