name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build JAR file
      run: mvn clean package -DskipTests

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
        kubectl config use-context my-cluster

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/mysql.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl rollout restart deployment/springboot-app
        
    - name: Check Deployment Status
      run: |
        kubectl get deployments
        kubectl get pods
        kubectl describe deployment springboot-app


    - name: Destroy Kind cluster
      run: kind delete cluster --name my-cluster
